const assert=require('node:assert/strict'),fs=require('node:fs'),E=require('../src/course-banks'),U=require('../src/curriculum87-common'),C=require('../src/curriculum87-map'),F=require('../src/foundations87-map');
const outcomes=JSON.parse(fs.readFileSync(require.resolve('../curriculum/mcada-g5/v0.2/coverage-map.json'))).outcomes;
assert.equal(C.length,340);assert.equal(E.catalog.length,891);assert.equal(new Set(E.catalog.map(c=>c.sourceId)).size,891);const authored=[...F,...C];assert.equal(authored.length,370);
assert.deepEqual(authored.filter(c=>c.standard).map(c=>c.standard).sort(),outcomes.map(o=>o.source_code).sort());assert.equal(C.filter(c=>!c.standard).length,39);
assert.deepEqual([...new Set(authored.map(c=>Number(c.lessonId.split(':').at(-1))))].sort((a,b)=>a-b),[...Array.from({length:120},(_,i)=>i+1),...Array.from({length:13},(_,i)=>201+i)]);
for(const c of C){assert.equal(c.exactLegacyReproduction,false);assert.equal(c.fullOutcomeVerified,false);if(c.standard)assert.ok(outcomes.some(o=>o.source_code===c.standard&&o.gradecam_alias===c.alias));else assert.equal(c.alias,null);const q=E.generate(c.sourceId,{seed:'contract',index:0});assert.ok(Object.isFrozen(q)&&Object.isFrozen(q.answer));assert.equal(q.givens.recipe,c.recipe);assert.ok(!E.renderQuestion(q).includes('teacher-diagram'));if(q.teacherSvg)assert.ok(!E.renderQuestion(q).includes(q.teacherSvg));if(q.answer.kind==='teacher'){assert.equal(E.checkAnswer(q,E.answerText(q)).answerCorrect,null);assert.equal(E.checkAnswer(q,'42').requiresTeacherReview,true);}else{assert.equal(E.checkAnswer(q,'' ).answerCorrect,false);assert.equal(E.checkAnswer(q,'1e309').answerCorrect,false);assert.equal(E.checkAnswer(q,'NaN').answerCorrect,false);}}
const formats=U.n('Represent one half',[U.R(1,2),U.R(1,2),U.R(50)],'1/2 = 0.5 = 50%',{},['fraction','decimal','numbers']);assert.equal(U.check(formats,'1/2; 0.5; 50').answerCorrect,true);for(const bad of ['0.5;0.5;50','2/4;0.5;50','1/2;1/2;50','1/2;0.5;50;0','1/2;0.5;50%'])assert.equal(U.check(formats,bad).answerCorrect,false,bad);
assert.equal(U.check(U.text('list','2; 3','reference'),'2;3').answerCorrect,true);
// Common diagram invariants: subdivisions, circle-area shading and valid nets.
const strip=U.strip(7,5,2);assert.equal((strip.match(/<rect /g)||[]).length,10);assert.equal((strip.match(/fill="#1c9188"/g)||[]).length,7);
const net=require('../src/curriculum87-late').net(4,6,5);assert.equal((net.match(/<rect /g)||[]).length,6);
// Independent compound-interest and required-method boundary regressions.
for(let index=0;index<30;index++){const q=E.generate('course-87-en:authored:COURSE110.2',{seed:'regression',index}),p=q.givens.parameters,a=q.answer.values[0];assert.equal(Number(a.numerator)/Number(a.denominator),Math.round(p.principal*(1+p.rate/100)**p.years*100)/100);}
console.log('PASS: all 331 codes and 133 course scopes, unique authored IDs, no invented codes, review-only grading, exact representation formats, replay-safe metadata and diagram invariants.');
