const E=require('../src/course-banks'),C=E.connections,assert=require('node:assert/strict'),fs=require('fs');
assert.equal(E.catalog.length,2184);assert.equal(C.profiles.length,2184);assert.equal(C.topics.length,66);assert(C.tracks.length>=74);assert.equal(new Set(C.profiles.map(p=>p.sourceId)).size,2184);
for(const p of C.profiles){assert(E.catalog.some(c=>c.sourceId===p.sourceId));assert(p.lessonId);assert(C.lookup(p.providerSourceId));assert.equal(p.localGrade,C.coursePlacement.find(c=>c.bankId===p.bankId).localGrade);assert(Object.isFrozen(p));assert(C.browse(p.topic).some(x=>x.sourceId===p.sourceId));assert.equal(C.compare(p.sourceId,p.sourceId).type,'same-source');}
let comparisons=0;const inverses={harder:'easier',easier:'harder',extension:'prerequisite',prerequisite:'extension','same-scope':'same-scope',related:'related','shared-provider':'shared-provider'};
for(const t of C.tracks)for(const a of t.stages)for(const b of t.stages){for(const id of a.sourceIds)for(const other of b.sourceIds){if(id===other)continue;const r=C.compare(id,other),rev=C.compare(other,id);assert.equal(rev.type,inverses[r.type],[id,other].join(' '));assert.equal(r.automaticRemovalAllowed,false);if(C.lookup(id).providerSourceId===C.lookup(other).providerSourceId)assert.equal(r.type,'shared-provider');comparisons++;}}
for(const g of C.reuseGroups){for(const id of g.sourceIds)assert.equal(C.lookup(id).providerSourceId,g.providerSourceId);const r=C.compare(g.sourceIds[0],g.sourceIds[1]);assert.equal(r.type,'shared-provider');}
const rectangle='course-1-en:authored:M7-perimeter-rectangle',quad='course-87-en:authored:M7-perimeter-irregular';assert.equal(C.compare(rectangle,quad).type,'harder');assert.equal(C.compare(quad,rectangle).type,'easier');assert(C.suggestions(rectangle,{relation:'harder',targetBank:'course-87-en'}).some(p=>p.sourceId===quad));assert(C.suggestions(quad,{relation:'easier',targetBank:'course-1-en'}).some(p=>p.sourceId===rectangle));
for(const p of C.profiles.filter(p=>p.memberships.length)){const opts={relation:'all',limit:20},s=C.suggestions(p.sourceId,opts);assert.deepEqual(s,C.suggestions(p.sourceId,opts));assert(s.every(r=>r.sourceId!==p.sourceId&&r.profile.bankId!==p.bankId&&r.type!=='shared-provider'));assert.equal(new Set(s.map(r=>r.profile.providerSourceId)).size,s.length);}
const unranked=C.profiles.filter(p=>!p.memberships.length);for(const p of unranked){assert.equal(C.suggestions(p.sourceId,{relation:'harder'}).length,0);assert.equal(C.suggestions(p.sourceId,{relation:'easier'}).length,0);}
assert.throws(()=>C.lookup('bogus'));assert.throws(()=>C.suggestions(rectangle,{relation:'very hard'}));assert.throws(()=>C.suggestions(rectangle,{limit:0}));assert.throws(()=>C.suggestions(rectangle,{crossBankOnly:'false'}));
let math=0;for(let index=0;index<128;index++){const q=E.generate(quad,{seed:'m7-independent',index});assert.deepEqual(q,E.generate(quad,{seed:'m7-independent',index}));const {w,sides}=q.givens.parameters;assert.equal(Number(q.answer.values[0].numerator)/Number(q.answer.values[0].denominator),sides.reduce((x,y)=>x+y,0));assert.equal(Math.hypot(3,4),sides[1]);assert(sides.every(x=>x>0)&&new Set(sides).size===4);assert(E.checkAnswer(q,String(2*w+12)).answerCorrect);assert(!E.checkAnswer(q,String(2*w+13)).answerCorrect);assert.equal((q.givens.svg.match(/<text /g)||[]).length,4);assert(E.renderQuestion(q).includes('<svg'));const reused=E.generate(rectangle,{seed:'m7-independent',index});assert(E.checkAnswer(reused,E.answerText(reused)).answerCorrect);math+=2;}
const baseline=process.env.M7_BASELINE;let retained=0;if(baseline){const B=require(baseline+'/src/course-banks'),normal=q=>{q=JSON.parse(JSON.stringify(q));delete q.version;return q;};for(const c of B.catalog){assert.deepEqual(E.catalog.find(x=>x.sourceId===c.sourceId),c);for(let index=0;index<3;index++){const opts={seed:'m7-retained',index};assert.deepEqual(normal(E.generate(c.sourceId,opts)),normal(B.generate(c.sourceId,opts)),c.sourceId);retained++;}}}
const result={result:'passed',catalog:E.catalog.length,topics:C.topics.length,tracks:C.tracks.length,progressionEntries:C.profiles.length-unranked.length,unranked:unranked.length,comparisons,newMathCases:math,retainedParityCases:retained};fs.writeFileSync('/tmp/m7-engine-results.json',JSON.stringify(result,null,2));console.log(result);
