const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),E=require('../src/course-banks'),A=E.assessment,U=require('../src/curriculum87-common');
const report=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../curriculum/mcada-g5/phase2-v0.1/coverage-review.json'))),source=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../curriculum/mcada-g5/v0.2/coverage-map.json'))).outcomes;
assert.equal(report.outcomes.length,370);assert.equal(source.length,331);assert.equal(new Set(report.outcomes.map(r=>r.sourceId)).size,370);
for(const s of source){const row=report.outcomes.find(r=>r.standard===s.source_code);assert.ok(row);assert.equal(row.originalObjective,s.objective.trim());assert.equal(row.alias,s.gradecam_alias);assert.equal(A.lookup(row.standard),A.lookup(row.alias));assert.equal(A.lookup(row.standard).sourceId,row.sourceId);assert.equal(row.curriculumCoverageAccepted,true);assert.equal(row.automaticAssignmentReady,false);assert.ok(row.reviewedScope.length>30);for(const id of row.canonicalSkillIds)assert.ok(A.skills.some(s=>s.id===id));}
for(const bad of ['PS.MAT.G5.999.9','CCSS.5.NF.A.1','',null])assert.throws(()=>A.lookup(bad));
const id=r=>'course-87-en:authored:MCADA-'+r;
for(const pair of [['6.2','24.2'],['7.4','17.2'],['31.2','43.1'],['71.1','74.1'],['43.4','48.2']])assert.equal(A.compare(...pair.map(id)).relationship,'same-assessment-scope');
for(const pair of [['1.6','35.2'],['3.1','3.4'],['43.4','43.1'],['95.1','70.2']])assert.equal(A.compare(...pair.map(id)).relationship,'partial-overlap');
for(const pair of [['21.3','21.4'],['27.3','27.4'],['71.1','71.2'],['38.3','INV5.2']])assert.equal(A.compare(...pair.map(id)).relationship,'distinct');
assert.equal(A.overlaps([id('6.2'),id('24.2'),id('7.2')]).length,1);assert.equal(A.compare(id('6.2'),id('24.2')).automaticRemovalAllowed,false);assert.ok(Object.isFrozen(A.lookup(id('6.2')).canonicalSkillIds));
const expected={'16.1':14,'18.6':6,'19.1':3,'27.2':2,'28.1':4,'29.3':4,'37.2':3,'38.2':3,'39.2':4,'43.4':3,'49.1':4,'52.1':4,'58.1':4,'62.2':6,'67.1':6,'67.2':2,'79.2':4,'80.1':4,'80.2':4,'80.3':4,'81.1':3,'88.1':6,'88.2':6,'92.2':6,'94.2':3,'94.3':2,'95.1':3,'97.1':4,'98.1':2,'105.1':3,'INV3.1':7,'INV3.2':6,'INV4.4':4,'INV9.1':2,'13.1':3,'18.4':4,'INV2.3':3,'INV5.3':4};
for(const [r,count] of Object.entries(expected)){const branches=new Set();for(let index=0;index<168;index++){const q=E.generate(id(r),{seed:'branches',index});branches.add(q.givens.parameters.branch);if(q.answer.kind==='teacher'){assert.equal(E.checkAnswer(q,E.answerText(q)).answerCorrect,null);assert.ok(q.answer.rubric.length>=2);}else assert.equal(E.checkAnswer(q,E.answerText(q)).answerCorrect,true,r);}assert.equal(branches.size,count,r);}
// Regression for mixed-number formats inside a tuple (previously used overall kind).
const tuple=U.n('Mixed then fraction',[U.R(7,3),U.R(1,2)],'reference',{},['mixed','fraction']);assert.equal(U.check(tuple,'2 1/3; 1/2').answerCorrect,true);for(const s of ['7/3;1/2','2 2/6;1/2','2 1/3;0.5'])assert.equal(U.check(tuple,s).answerCorrect,false);
// Geometry transforms checked independently by Euclidean distances and expected direction.
for(const r of ['80.1','80.2','80.3'])for(let index=0;index<32;index++){const q=E.generate(id(r),{seed:'isometry',index}),p=q.givens.parameters;for(let i=0;i<3;i++)for(let j=i+1;j<3;j++){const distance=(a,b)=>(a[0]-b[0])**2+(a[1]-b[1])**2;assert.equal(distance(p.pts[i],p.pts[j]),distance(p.image[i],p.image[j]));}if(r==='80.2')p.pts.forEach((x,i)=>assert.deepEqual(p.image[i],[x[0]+p.dx,x[1]+p.dy]));}
console.log(JSON.stringify({result:'passed',codedRows:331,manualRows:39,branchFamilies:Object.keys(expected).length,canonicalSkills:A.skills.length,checks:'source preservation, aliases, exact/partial overlap, method distinctions, branch reachability, mixed tuple regression, isometry, teacher-review boundary'}));
