const assert=require('node:assert/strict'),E=require('../src/course-banks'),U=require('../src/statistics-bank'),M=require('../src/structured-math');
for(const [s,p,want]of [['0.12349',3,'0.123'],['0.1235',3,'0.124'],['89.5',0,'90'],['89.495',2,'89.5']])assert.equal(M.format(U.round(M.decimal(s),p),'decimal'),want);
assert.throws(()=>U.statistics([1,2,3]));assert.throws(()=>U.statistics([1,1,2,2]));assert.deepEqual(U.statistics([9,1,2,2,6]).map(M.format),['8','4','2','2']);assert.deepEqual(U.statistics([9,1,2,2,6,10]).map(M.format),['9','5','4','2']);
function find(id,pred){for(let index=0;index<1000;index++){const q=E.generate(id,{index});if(pred(q))return q;}throw Error('Case not found');}
const q=find('algebra-1-en:node:493',q=>new Set(q.answer.values.map(v=>v.numerator+'/'+v.denominator)).size>=3),parts=U.answerText(q).split('; ');assert.ok(U.check(q,parts.join('; ')).answerCorrect);assert.ok(!U.check(q,parts.slice(1).join('; ')).answerCorrect);assert.ok(!U.check(q,[...parts,parts[0]].join('; ')).answerCorrect);assert.ok(!U.check(q,parts.reverse().join('; ')).answerCorrect);
const left=find('course-87-en:item:SN870522',q=>q.givens.parameters.event===4),right=find('algebra-half-en:node:702',q=>q.givens.parameters.event===4);assert.ok(U.check(left,'8/221').answerCorrect);assert.ok(!U.check(left,'4/221').answerCorrect);assert.ok(U.check(right,'4/221').answerCorrect);assert.ok(!U.check(right,'8/221').answerCorrect);
const dice=find('algebra-1-en:node:696',q=>q.givens.parameters.target===1);assert.ok(U.check(dice,'0').answerCorrect);assert.ok(!U.check(dice,'0%').answerCorrect);
const batting=E.generate('course-87-en:item:SX870226');assert.ok(!U.check(batting,batting.answer.values[0].numerator+'/'+batting.answer.values[0].denominator).answerCorrect);
for(const id of ['algebra-1-en:node:736','algebra-1-en:node:737']){const p=E.generate(id),a=U.answerText(p).split('; ');assert.ok(!U.check(p,a.reverse().join('; ')).answerCorrect);}
for(const c of U.catalog){const q=E.generate(c.sourceId);assert.ok(Object.isFrozen(q));assert.equal(E.checkAnswer(q,U.answerText(q)).fullOutcomeVerified,false);assert.ok(!U.render({...q,prompt:'<script>x</script>'}).includes('<script>'));}
assert.equal(U.catalog.length,38);assert.equal(new Set(E.catalog.map(c=>c.sourceId)).size,551);console.log('PASS: tuple order/cardinality, unique mode, odd/even median, ordered/unordered cards, zero probability, rounding/decimal boundaries and safe rendering');
